(*
  Category: SWAG Title: Borland DELPHI
  Original name: 0410.PAS
  Description: StatusBar able to hold controls
  Author: TANGENTALS DESIGN
  Date: 01-02-98  07:34
*)

{ ****************************************************************** }
{                                                                    }
{   VCL component TSStatusBar                                        }
{                                                                    }
{   StatusBar able to hold controls                                  }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from untitled component definition                     }
{   on 24 May 1997 at 11:36                                          }
{                                                                    }
{   Copyright ⌐ 1997 by ...Tangentals Design                         }
{                                                                    }
{ ****************************************************************** }

unit SStatBrU;

interface

uses WinTypes, WinProcs, Messages, SysUtils, Classes, Controls, 
     Forms, Graphics, Comctrls;

type
  TSStatusBar = class(TStatusBar)
    private
      { Private fields of TSStatusBar }

      { Private methods of TSStatusBar }
        { Method to set variable and property values and create objects }
        procedure AutoInitialize;
        { Method to free any objects created by AutoInitialize }
        procedure AutoDestroy;

    protected
      { Protected fields of TSStatusBar }

      { Protected methods of TSStatusBar }
        procedure Click; override;
        procedure Loaded; override;

    public
      { Public fields and properties of TSStatusBar }

      { Public methods of TSStatusBar }
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;

    published
      { Published properties of TSStatusBar }
        property OnClick;
        property OnResize;

  end;

procedure Register;

implementation

procedure Register;
begin
     { Register TSStatusBar with Win95 as its
       default page on the Delphi component palette }
     RegisterComponents('Win95', [TSStatusBar]);
end;

{ Method to set variable and property values and create objects }
procedure TSStatusBar.AutoInitialize;
begin
end; { of AutoInitialize }

{ Method to free any objects created by AutoInitialize }
procedure TSStatusBar.AutoDestroy;
begin
     { No objects from AutoInitialize to free }
end; { of AutoDestroy }

{ Override OnClick handler from TStatusBar }
procedure TSStatusBar.Click;
begin
     { Code to execute before activating click
       behavior of component's parent class }

     { Activate click behavior of parent }
     inherited Click;

     { Code to execute after click behavior
       of parent }

end;

constructor TSStatusBar.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }
     
ControlStyle := ControlStyle + [csAcceptsControls];

     
end;

destructor TSStatusBar.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TSStatusBar.Loaded;
begin
     inherited Loaded;

     { Perform any component setup that depends on the property
       values having been set }

end;


end.

